# Generated by Django 2.2 on 2019-04-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, default=2019)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('ratings', models.IntegerField(blank=True)),
            ],
        ),
    ]
